### PR TITLE
add turkish treebank sample xml file.

### PR DESCRIPTION
**Pull request by zeitnot**

### CODE REVIEW

**Comment by balmas** [comment]
Can you add some sentences to the sample file? It won't work without them.  For an example to follow see https://github.com/alpheios-project/arethusa-example-data/blob/master/data/treebanks/sanskrit.xml  

Thanks!

**Comment by zeitnot** [comment]
@balmas I checked your suggestions but definitely I did not understand anything. Is there any definition for that xml structure?

**Comment by balmas** [comment]
The schema is here:

http://nlp.perseus.tufts.edu/syntax/treebank/treebank-1.6.xsd

But basically, you just need to have a least one sentence, with some words, preferably annotated according to the tag set you just created.  

I don't know turkish, but just for an example, I took a sentence from http://www.humancomp.org/unichtm/huseyin.htm :

"Yukarda mavi gök, asağıda yağız yer yaratıldıkta; ikisinin arasında insan oğlu yaratılmış."

Unannotated it looks like this:

```
<treebank version="1.6"
   xml:lang="tr" format="turkish">

   <sentence id="1" document_id="turkish.demo1" subdoc="" span="">
      <word id="1" form="Yukarda" lemma="" postag="---------" relation="" head=""/>
      <word id="2" form="mavi" lemma="" postag="---------" relation="" head=""/>
      <word id="3" form="gök" lemma="" postag="---------" relation="" head=""/>
      <word id="4" form="asağıda" lemma="" postag="---------" relation="" head=""/>
      <word id="5" form="mavi" lemma="" postag="---------" relation="" head=""/>
      <word id="6" form="yağız" lemma="" postag="---------" relation="" head=""/>
      <word id="7" form="yer" lemma="" postag="---------" relation="" head=""/>
      <word id="8" form="yaratıldıkta" lemma="" postag="---------" relation="" head=""/>
      <word id="9" form=";" lemma="" postag="---------" relation="" head=""/>
      <word id="10" form="ikisinin" lemma="" postag="---------" relation="" head=""/>
      <word id="11" form="arasında" lemma="" postag="---------" relation="" head=""/>
      <word id="12" form="oğlu" lemma="" postag="---------" relation="" head=""/>
      <word id="13" form="yaratılmış" lemma="" postag="---------" relation="" head=""/>
      <word id="14" form="." lemma="" postag="---------" relation="" head=""/>
   </sentence>
</treebank>

```

The lemma, postag, relation and head tags can be completed using Arethusa with the tagsets you created, but it would be good to have an example completed treebank file showing their usage. 

@TDBuck could help explain this further if it's still not clear.

Thanks!

**Comment by zeitnot** [comment]
@balmas I understand a little bit but still I am curious about xml attributes such as `lemma`, `postag`, `head`, `span`, `subdoc`. I can understand what `relation` is but for the other attributes I need more definitions.

**Comment by balmas** [comment]
you don't need to worry about span and subdoc, they are largely legacy attributes that aren't important. You can use them, if you want, to provide explicit information about where in the source text the sentence comes from (e.g. which chapter, verse, line, etc.)

lemma gets set to the bare root form of the word, or the dictionary headword. 

postag is the part-of-speech tag, as produced through the mappings described here: https://github.com/alpheios-project/arethusa/wiki/Creating-a-Morphological-Attribute-Configuration-File

For more information, you can see https://perseusdl.github.io/treebank_data/ and in particular the Greek and Latin guidelines at https://github.com/PerseusDL/treebank_data/blob/master/AGDT2/guidelines/Greek_guidelines.md and http://nlp.perseus.tufts.edu/syntax/treebank/ldt/1.5/docs/guidelines.pdf

**Comment by zeitnot** [comment]
@balmas I have contributed a new commit. This is all what I can do. I have left blank `postag` and `head` due to fact that still I do not understand anything.

**Comment by balmas** [comment]
ok, this is fine for now. Thank you!

**Pull request merged**
